proc12_creat_fifo:proc12_creat_fifo.c
	gcc proc12_creat_fifo.c -o proc12_creat_fifo
proc11_pipe_child2father:proc11_pipe_child2father.c
	gcc proc11_pipe_child2father.c -o proc11_pipe_child2father
proc4_orphane:proc4_orphan.c
	gcc proc4_orphan.c -o proc4_orphan
proc2_getpid:proc2_getpid.c
	gcc proc2_getpid.c -o proc2_getpid
proc3_zombie:proc3_zombie.c
	gcc proc3_zombie.c -o proc3_zombie
